server:
  port: 9002
spring:
  application:
    name: review
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/reviews
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost