spring:
  cloud:
    gateway:
      routes:
        - id: movie_route
          uri: lb://movie-service
          predicates:
            - Path=/api/v1/movies/**
        - id: review_route
          uri: lb://review-service
          predicates:
            - Path=/api/v1/review/**
        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/login




